# Generated by Django 3.1.6 on 2021-02-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20210213_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
