# Generated by Django 3.1.6 on 2021-02-13 18:15

from django.db import migrations
import project.sqlite_fields


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_submission_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='data',
            field=project.sqlite_fields.JSONField(blank=True),
        ),
    ]
